/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ThemeSetting } from "./ThemeSetting";
import { ThemeSettingCountArgs } from "./ThemeSettingCountArgs";
import { ThemeSettingFindManyArgs } from "./ThemeSettingFindManyArgs";
import { ThemeSettingFindUniqueArgs } from "./ThemeSettingFindUniqueArgs";
import { DeleteThemeSettingArgs } from "./DeleteThemeSettingArgs";
import { ThemeSettingService } from "../themeSetting.service";
@graphql.Resolver(() => ThemeSetting)
export class ThemeSettingResolverBase {
  constructor(protected readonly service: ThemeSettingService) {}

  async _themeSettingsMeta(
    @graphql.Args() args: ThemeSettingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ThemeSetting])
  async themeSettings(
    @graphql.Args() args: ThemeSettingFindManyArgs
  ): Promise<ThemeSetting[]> {
    return this.service.themeSettings(args);
  }

  @graphql.Query(() => ThemeSetting, { nullable: true })
  async themeSetting(
    @graphql.Args() args: ThemeSettingFindUniqueArgs
  ): Promise<ThemeSetting | null> {
    const result = await this.service.themeSetting(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ThemeSetting)
  async deleteThemeSetting(
    @graphql.Args() args: DeleteThemeSettingArgs
  ): Promise<ThemeSetting | null> {
    try {
      return await this.service.deleteThemeSetting(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
